var appConstants = {
  CHANGE_EVENT: "CHANGE_EVENT",

  REQUEST: {
    READY: "READY",
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR"
  },
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  //current user
  SET_CURRENT_USER: "SET_CURRENT_USER",
  DESTROY_CURRENT_USER: "DESTROY_CURRENT_USER",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  //posts
  GET_POSTS_LIST: "GET_POSTS_LIST"
};

module.exports = appConstants;