var appConstants = {
  CHANGE_EVENT: "CHANGE_EVENT",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  DESTROY_CURRENT_USER: "DESTROY_CURRENT_USER"
};

module.exports = appConstants;